{{
    config(
        materialized='incremental',
        unique_key=['year', 'tournament_id', 'match_id', 'set_number']
    )
}}

with staging as (
    select * from {{ ref('stg_atp_key_stats') }}
    {% if is_incremental() %}
    where meta_file_modified > (select max(meta_file_modified) from {{ this }})
    {% endif %}
),

parsed_ratios as (
    select
        year, tournament_id, upper(match_id) as match_id, sets_completed, set_number,
        player1_seed, player1_name, player1_first_name, player1_last_name, upper(player1_id) as player1_id, upper(player1_country) as player1_country,
        player2_seed, player2_name, player2_first_name, player2_last_name, upper(player2_id) as player2_id, upper(player2_country) as player2_country,
        meta_file_modified,

        try_cast(serve_rating_player1 as float) as serve_rating_player1,
        try_cast(serve_rating_player2 as float) as serve_rating_player2,
        try_cast(aces_player1 as float) as aces_player1,
        try_cast(aces_player2 as float) as aces_player2,
        try_cast(double_faults_player1 as float) as double_faults_player1,
        try_cast(double_faults_player2 as float) as double_faults_player2,
        try_cast(split_part(split_part(first_serve_player1, ' ', 1), '/', 1) as float) as first_serve_player1_won,
        try_cast(split_part(split_part(first_serve_player1, ' ', 1), '/', 2) as float) as first_serve_player1_total,
        try_cast(split_part(split_part(first_serve_player2, ' ', 1), '/', 1) as float) as first_serve_player2_won,
        try_cast(split_part(split_part(first_serve_player2, ' ', 1), '/', 2) as float) as first_serve_player2_total,
        try_cast(split_part(split_part(first_serve_points_won_player1, ' ', 1), '/', 1) as float) as first_serve_points_won_player1_won,
        try_cast(split_part(split_part(first_serve_points_won_player1, ' ', 1), '/', 2) as float) as first_serve_points_won_player1_total,
        try_cast(split_part(split_part(first_serve_points_won_player2, ' ', 1), '/', 1) as float) as first_serve_points_won_player2_won,
        try_cast(split_part(split_part(first_serve_points_won_player2, ' ', 1), '/', 2) as float) as first_serve_points_won_player2_total,
        try_cast(split_part(split_part(second_serve_points_won_player1, ' ', 1), '/', 1) as float) as second_serve_points_won_player1_won,
        try_cast(split_part(split_part(second_serve_points_won_player1, ' ', 1), '/', 2) as float) as second_serve_points_won_player1_total,
        try_cast(split_part(split_part(second_serve_points_won_player2, ' ', 1), '/', 1) as float) as second_serve_points_won_player2_won,
        try_cast(split_part(split_part(second_serve_points_won_player2, ' ', 1), '/', 2) as float) as second_serve_points_won_player2_total,
        try_cast(split_part(split_part(break_points_saved_player1, ' ', 1), '/', 1) as float) as break_points_saved_player1_won,
        try_cast(split_part(split_part(break_points_saved_player1, ' ', 1), '/', 2) as float) as break_points_saved_player1_total,
        try_cast(split_part(split_part(break_points_saved_player2, ' ', 1), '/', 1) as float) as break_points_saved_player2_won,
        try_cast(split_part(split_part(break_points_saved_player2, ' ', 1), '/', 2) as float) as break_points_saved_player2_total,
        try_cast(service_games_played_player1 as float) as service_games_played_player1,
        try_cast(service_games_played_player2 as float) as service_games_played_player2,
        try_cast(return_rating_player1 as float) as return_rating_player1,
        try_cast(return_rating_player2 as float) as return_rating_player2,
        try_cast(split_part(split_part(first_serve_return_points_won_player1, ' ', 1), '/', 1) as float) as first_serve_return_points_won_player1_won,
        try_cast(split_part(split_part(first_serve_return_points_won_player1, ' ', 1), '/', 2) as float) as first_serve_return_points_won_player1_total,
        try_cast(split_part(split_part(first_serve_return_points_won_player2, ' ', 1), '/', 1) as float) as first_serve_return_points_won_player2_won,
        try_cast(split_part(split_part(first_serve_return_points_won_player2, ' ', 1), '/', 2) as float) as first_serve_return_points_won_player2_total,
        try_cast(split_part(split_part(second_serve_return_points_won_player1, ' ', 1), '/', 1) as float) as second_serve_return_points_won_player1_won,
        try_cast(split_part(split_part(second_serve_return_points_won_player1, ' ', 1), '/', 2) as float) as second_serve_return_points_won_player1_total,
        try_cast(split_part(split_part(second_serve_return_points_won_player2, ' ', 1), '/', 1) as float) as second_serve_return_points_won_player2_won,
        try_cast(split_part(split_part(second_serve_return_points_won_player2, ' ', 1), '/', 2) as float) as second_serve_return_points_won_player2_total,
        try_cast(split_part(split_part(break_points_converted_player1, ' ', 1), '/', 1) as float) as break_points_converted_player1_won,
        try_cast(split_part(split_part(break_points_converted_player1, ' ', 1), '/', 2) as float) as break_points_converted_player1_total,
        try_cast(split_part(split_part(break_points_converted_player2, ' ', 1), '/', 1) as float) as break_points_converted_player2_won,
        try_cast(split_part(split_part(break_points_converted_player2, ' ', 1), '/', 2) as float) as break_points_converted_player2_total,
        try_cast(return_games_played_player1 as float) as return_games_played_player1,
        try_cast(return_games_played_player2 as float) as return_games_played_player2,
        try_cast(split_part(split_part(net_points_won_player1, ' ', 1), '/', 1) as float) as net_points_won_player1_won,
        try_cast(split_part(split_part(net_points_won_player1, ' ', 1), '/', 2) as float) as net_points_won_player1_total,
        try_cast(split_part(split_part(net_points_won_player2, ' ', 1), '/', 1) as float) as net_points_won_player2_won,
        try_cast(split_part(split_part(net_points_won_player2, ' ', 1), '/', 2) as float) as net_points_won_player2_total,
        try_cast(winners_player1 as float) as winners_player1,
        try_cast(winners_player2 as float) as winners_player2,
        try_cast(unforced_errors_player1 as float) as unforced_errors_player1,
        try_cast(unforced_errors_player2 as float) as unforced_errors_player2,
        try_cast(split_part(split_part(service_points_won_player1, ' ', 1), '/', 1) as float) as service_points_won_player1_won,
        try_cast(split_part(split_part(service_points_won_player1, ' ', 1), '/', 2) as float) as service_points_won_player1_total,
        try_cast(split_part(split_part(service_points_won_player2, ' ', 1), '/', 1) as float) as service_points_won_player2_won,
        try_cast(split_part(split_part(service_points_won_player2, ' ', 1), '/', 2) as float) as service_points_won_player2_total,
        try_cast(split_part(split_part(return_points_won_player1, ' ', 1), '/', 1) as float) as return_points_won_player1_won,
        try_cast(split_part(split_part(return_points_won_player1, ' ', 1), '/', 2) as float) as return_points_won_player1_total,
        try_cast(split_part(split_part(return_points_won_player2, ' ', 1), '/', 1) as float) as return_points_won_player2_won,
        try_cast(split_part(split_part(return_points_won_player2, ' ', 1), '/', 2) as float) as return_points_won_player2_total,
        try_cast(split_part(split_part(total_points_won_player1, ' ', 1), '/', 1) as float) as total_points_won_player1_won,
        try_cast(split_part(split_part(total_points_won_player1, ' ', 1), '/', 2) as float) as total_points_won_player1_total,
        try_cast(split_part(split_part(total_points_won_player2, ' ', 1), '/', 1) as float) as total_points_won_player2_won,
        try_cast(split_part(split_part(total_points_won_player2, ' ', 1), '/', 2) as float) as total_points_won_player2_total,
        try_cast(max_speed_player1 as float) as max_speed_player1,
        try_cast(max_speed_player2 as float) as max_speed_player2,
        try_cast(first_serve_avg_speed_player1 as float) as first_serve_avg_speed_player1,
        try_cast(first_serve_avg_speed_player2 as float) as first_serve_avg_speed_player2,
        try_cast(second_serve_avg_speed_player1 as float) as second_serve_avg_speed_player1,
        try_cast(second_serve_avg_speed_player2 as float) as second_serve_avg_speed_player2
    from staging
    where aces_player1 is not null or aces_player2 is not null
    qualify row_number() over(partition by year, tournament_id, match_id, set_number order by meta_file_modified desc) = 1
),

derived_and_slams as (
    select *,
        coalesce(first_serve_return_points_won_player1_won, first_serve_points_won_player2_total - first_serve_points_won_player2_won) as first_serve_return_points_won_player1_won_final,
        coalesce(first_serve_return_points_won_player1_total, first_serve_points_won_player2_total) as first_serve_return_points_won_player1_total_final,
        coalesce(second_serve_return_points_won_player1_won, second_serve_points_won_player2_total - second_serve_points_won_player2_won) as second_serve_return_points_won_player1_won_final,
        coalesce(second_serve_return_points_won_player1_total, second_serve_points_won_player2_total) as second_serve_return_points_won_player1_total_final,
        coalesce(break_points_saved_player1_won, break_points_converted_player2_total - break_points_converted_player2_won) as break_points_saved_player1_won_final,
        coalesce(break_points_saved_player1_total, break_points_converted_player2_total) as break_points_saved_player1_total_final,
        coalesce(service_points_won_player1_won, (first_serve_points_won_player1_won + second_serve_points_won_player1_won)) as service_points_won_player1_won_final,
        coalesce(service_points_won_player1_total, (first_serve_points_won_player1_total + second_serve_points_won_player1_total)) as service_points_won_player1_total_final,
        coalesce(return_points_won_player1_won, (coalesce(first_serve_return_points_won_player1_won, first_serve_points_won_player2_total - first_serve_points_won_player2_won) + coalesce(second_serve_return_points_won_player1_won, second_serve_points_won_player2_total - second_serve_points_won_player2_won))) as return_points_won_player1_won_final,
        coalesce(return_points_won_player1_total, (coalesce(first_serve_return_points_won_player1_total, first_serve_points_won_player2_total) + coalesce(second_serve_return_points_won_player1_total, second_serve_points_won_player2_total))) as return_points_won_player1_total_final,
        coalesce(total_points_won_player1_won, ((first_serve_points_won_player1_won + second_serve_points_won_player1_won) + (coalesce(first_serve_return_points_won_player1_won, first_serve_points_won_player2_total - first_serve_points_won_player2_won) + coalesce(second_serve_return_points_won_player1_won, second_serve_points_won_player2_total - second_serve_points_won_player2_won)))) as total_points_won_player1_won_final,
        coalesce(total_points_won_player1_total, ((first_serve_points_won_player1_total + second_serve_points_won_player1_total) + (coalesce(first_serve_return_points_won_player1_total, first_serve_points_won_player2_total) + coalesce(second_serve_return_points_won_player1_total, second_serve_points_won_player2_total)))) as total_points_won_player1_total_final,
        coalesce(first_serve_return_points_won_player2_won, first_serve_points_won_player1_total - first_serve_points_won_player1_won) as first_serve_return_points_won_player2_won_final,
        coalesce(first_serve_return_points_won_player2_total, first_serve_points_won_player1_total) as first_serve_return_points_won_player2_total_final,
        coalesce(second_serve_return_points_won_player2_won, second_serve_points_won_player1_total - second_serve_points_won_player1_won) as second_serve_return_points_won_player2_won_final,
        coalesce(second_serve_return_points_won_player2_total, second_serve_points_won_player1_total) as second_serve_return_points_won_player2_total_final,
        coalesce(break_points_saved_player2_won, break_points_converted_player1_total - break_points_converted_player1_won) as break_points_saved_player2_won_final,
        coalesce(break_points_saved_player2_total, break_points_converted_player1_total) as break_points_saved_player2_total_final,
        coalesce(service_points_won_player2_won, (first_serve_points_won_player2_won + second_serve_points_won_player2_won)) as service_points_won_player2_won_final,
        coalesce(service_points_won_player2_total, (first_serve_points_won_player2_total + second_serve_points_won_player2_total)) as service_points_won_player2_total_final,
        coalesce(return_points_won_player2_won, (coalesce(first_serve_return_points_won_player2_won, first_serve_points_won_player1_total - first_serve_points_won_player1_won) + coalesce(second_serve_return_points_won_player2_won, second_serve_points_won_player1_total - second_serve_points_won_player1_won))) as return_points_won_player2_won_final,
        coalesce(return_points_won_player2_total, (coalesce(first_serve_return_points_won_player2_total, first_serve_points_won_player1_total) + coalesce(second_serve_return_points_won_player2_total, second_serve_points_won_player1_total))) as return_points_won_player2_total_final,
        coalesce(total_points_won_player2_won, ((first_serve_points_won_player2_won + second_serve_points_won_player2_won) + (coalesce(first_serve_return_points_won_player2_won, first_serve_points_won_player1_total - first_serve_points_won_player1_won) + coalesce(second_serve_return_points_won_player2_won, second_serve_points_won_player1_total - second_serve_points_won_player1_won)))) as total_points_won_player2_won_final,
        coalesce(total_points_won_player2_total, ((first_serve_points_won_player2_total + second_serve_points_won_player2_total) + (coalesce(first_serve_return_points_won_player2_total, first_serve_points_won_player1_total) + coalesce(second_serve_return_points_won_player2_total, second_serve_points_won_player1_total)))) as total_points_won_player2_total_final
    from parsed_ratios
),

final as (
    select
        year, tournament_id, match_id, sets_completed, set_number,
        player1_seed, player1_name, player1_first_name, player1_last_name, player1_id, player1_country,
        player2_seed, player2_name, player2_first_name, player2_last_name, player2_id, player2_country,
        meta_file_modified,
        serve_rating_player1 as serve_rating_player1,
        serve_rating_player2 as serve_rating_player2,
        aces_player1 as aces_player1,
        aces_player2 as aces_player2,
        double_faults_player1 as double_faults_player1,
        double_faults_player2 as double_faults_player2,
        first_serve_player1_won as serve1_player1_won,
        first_serve_player1_total as serve1_player1_played,
        round((first_serve_player1_won * 100.0) / nullif(first_serve_player1_total, 0), 1) as serve1_player1_pct,
        first_serve_player2_won as serve1_player2_won,
        first_serve_player2_total as serve1_player2_played,
        round((first_serve_player2_won * 100.0) / nullif(first_serve_player2_total, 0), 1) as serve1_player2_pct,
        first_serve_points_won_player1_won as serve1_pts_won_player1_won,
        first_serve_points_won_player1_total as serve1_pts_won_player1_played,
        round((first_serve_points_won_player1_won * 100.0) / nullif(first_serve_points_won_player1_total, 0), 1) as serve1_pts_won_player1_pct,
        first_serve_points_won_player2_won as serve1_pts_won_player2_won,
        first_serve_points_won_player2_total as serve1_pts_won_player2_played,
        round((first_serve_points_won_player2_won * 100.0) / nullif(first_serve_points_won_player2_total, 0), 1) as serve1_pts_won_player2_pct,
        second_serve_points_won_player1_won as serve2_pts_won_player1_won,
        second_serve_points_won_player1_total as serve2_pts_won_player1_played,
        round((second_serve_points_won_player1_won * 100.0) / nullif(second_serve_points_won_player1_total, 0), 1) as serve2_pts_won_player1_pct,
        second_serve_points_won_player2_won as serve2_pts_won_player2_won,
        second_serve_points_won_player2_total as serve2_pts_won_player2_played,
        round((second_serve_points_won_player2_won * 100.0) / nullif(second_serve_points_won_player2_total, 0), 1) as serve2_pts_won_player2_pct,
        break_points_saved_player1_won_final as break_points_saved_player1_won,
        break_points_saved_player1_total_final as break_points_saved_player1_played,
        round((break_points_saved_player1_won_final * 100.0) / nullif(break_points_saved_player1_total_final, 0), 1) as break_points_saved_player1_pct,
        break_points_saved_player1_total_final as break_points_faced_player1,
        break_points_saved_player2_won_final as break_points_saved_player2_won,
        break_points_saved_player2_total_final as break_points_saved_player2_played,
        round((break_points_saved_player2_won_final * 100.0) / nullif(break_points_saved_player2_total_final, 0), 1) as break_points_saved_player2_pct,
        break_points_saved_player2_total_final as break_points_faced_player2,
        service_games_played_player1 as service_games_played_player1,
        service_games_played_player2 as service_games_played_player2,
        return_rating_player1 as return_rating_player1,
        return_rating_player2 as return_rating_player2,
        first_serve_return_points_won_player1_won_final as serve1_return_pts_won_player1_won,
        first_serve_return_points_won_player1_total_final as serve1_return_pts_won_player1_played,
        round((first_serve_return_points_won_player1_won_final * 100.0) / nullif(first_serve_return_points_won_player1_total_final, 0), 1) as serve1_return_pts_won_player1_pct,
        first_serve_return_points_won_player2_won_final as serve1_return_pts_won_player2_won,
        first_serve_return_points_won_player2_total_final as serve1_return_pts_won_player2_played,
        round((first_serve_return_points_won_player2_won_final * 100.0) / nullif(first_serve_return_points_won_player2_total_final, 0), 1) as serve1_return_pts_won_player2_pct,
        second_serve_return_points_won_player1_won_final as serve2_return_pts_won_player1_won,
        second_serve_return_points_won_player1_total_final as serve2_return_pts_won_player1_played,
        round((second_serve_return_points_won_player1_won_final * 100.0) / nullif(second_serve_return_points_won_player1_total_final, 0), 1) as serve2_return_pts_won_player1_pct,
        second_serve_return_points_won_player2_won_final as serve2_return_pts_won_player2_won,
        second_serve_return_points_won_player2_total_final as serve2_return_pts_won_player2_played,
        round((second_serve_return_points_won_player2_won_final * 100.0) / nullif(second_serve_return_points_won_player2_total_final, 0), 1) as serve2_return_pts_won_player2_pct,
        break_points_converted_player1_won as break_points_converted_player1_won,
        break_points_converted_player1_total as break_points_converted_player1_played,
        round((break_points_converted_player1_won * 100.0) / nullif(break_points_converted_player1_total, 0), 1) as break_points_converted_player1_pct,
        break_points_converted_player2_won as break_points_converted_player2_won,
        break_points_converted_player2_total as break_points_converted_player2_played,
        round((break_points_converted_player2_won * 100.0) / nullif(break_points_converted_player2_total, 0), 1) as break_points_converted_player2_pct,
        return_games_played_player1 as return_games_played_player1,
        return_games_played_player2 as return_games_played_player2,
        net_points_won_player1_won as net_points_won_player1_won,
        net_points_won_player1_total as net_points_won_player1_played,
        round((net_points_won_player1_won * 100.0) / nullif(net_points_won_player1_total, 0), 1) as net_points_won_player1_pct,
        net_points_won_player2_won as net_points_won_player2_won,
        net_points_won_player2_total as net_points_won_player2_played,
        round((net_points_won_player2_won * 100.0) / nullif(net_points_won_player2_total, 0), 1) as net_points_won_player2_pct,
        winners_player1 as winners_player1,
        winners_player2 as winners_player2,
        unforced_errors_player1 as unforced_errors_player1,
        unforced_errors_player2 as unforced_errors_player2,
        service_points_won_player1_won_final as service_points_won_player1_won,
        service_points_won_player1_total_final as service_points_won_player1_played,
        round((service_points_won_player1_won_final * 100.0) / nullif(service_points_won_player1_total_final, 0), 1) as service_points_won_player1_pct,
        service_points_won_player2_won_final as service_points_won_player2_won,
        service_points_won_player2_total_final as service_points_won_player2_played,
        round((service_points_won_player2_won_final * 100.0) / nullif(service_points_won_player2_total_final, 0), 1) as service_points_won_player2_pct,
        return_points_won_player1_won_final as return_points_won_player1_won,
        return_points_won_player1_total_final as return_points_won_player1_played,
        round((return_points_won_player1_won_final * 100.0) / nullif(return_points_won_player1_total_final, 0), 1) as return_points_won_player1_pct,
        return_points_won_player2_won_final as return_points_won_player2_won,
        return_points_won_player2_total_final as return_points_won_player2_played,
        round((return_points_won_player2_won_final * 100.0) / nullif(return_points_won_player2_total_final, 0), 1) as return_points_won_player2_pct,
        total_points_won_player1_won_final as total_points_won_player1_won,
        total_points_won_player1_total_final as total_points_won_player1_played,
        round((total_points_won_player1_won_final * 100.0) / nullif(total_points_won_player1_total_final, 0), 1) as total_points_won_player1_pct,
        total_points_won_player2_won_final as total_points_won_player2_won,
        total_points_won_player2_total_final as total_points_won_player2_played,
        round((total_points_won_player2_won_final * 100.0) / nullif(total_points_won_player2_total_final, 0), 1) as total_points_won_player2_pct,
        case when abs(max_speed_player1) > 300 then null else max_speed_player1 end as max_speed_player1,
        case when abs(max_speed_player2) > 300 then null else max_speed_player2 end as max_speed_player2,
        case when abs(first_serve_avg_speed_player1) > 300 then null else first_serve_avg_speed_player1 end as serve1_avg_speed_player1,
        case when abs(first_serve_avg_speed_player2) > 300 then null else first_serve_avg_speed_player2 end as serve1_avg_speed_player2,
        case when abs(second_serve_avg_speed_player1) > 300 then null else second_serve_avg_speed_player1 end as serve2_avg_speed_player1,
        case when abs(second_serve_avg_speed_player2) > 300 then null else second_serve_avg_speed_player2 end as serve2_avg_speed_player2
    from derived_and_slams
)

select * from final
